swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    port: "%mailer_port%"
    spool: { type: memory }
    disable_delivery: "%mailer_disable_delivery%"
    delivery_addresses: ["%mailer_master_email_address%"]
    delivery_whitelist: "%mailer_delivery_whitelist%"
